version: '3'
services:

  db:
    image: mysql
    volumes:
      - ../mysql-data:/var/lib/mysql
    ports:
      - "10000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: cloud-ms
